services:
  postgres:
    image: postgres:16
    container_name: AndefRacing-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORTS}
    volumes:
      - postgres_data_andef_racing:/var/lib/postgresql/data
      - ./src/main/scripts/db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data_andef_racing: